version: '3'

services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - database
    depends_on:
      - database
    restart: always

  database:
    build: sql
    volumes:
      - ./sql/data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  phpmysqladmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database
